"""四平台适配器测试：用 respx 拦截 HTTP，验证解析与字段映射。"""

from __future__ import annotations

import json

import httpx
import pytest
import respx

from fissue.models import AuthorKind, ItemType, Platform, RepoRef
from fissue.platforms.registry import (
    ADAPTERS,
    build_adapter,
    get_adapter_class,
    parse_repo_ref,
    resolve_repos,
)
from fissue.platforms.base import extract_linked_issues, guess_author_kind, parse_dt
from fissue.platforms.gitlab import GitLabAdapter, _norm_state

GH = "https://api.github.com"
GITEE = "https://gitee.com/api/v5"
ATOMGIT = "https://api.atomgit.com/api/v5"
GL = "https://gitlab.com/api/v4"

REPO = RepoRef(platform=Platform.GITHUB, owner="psf", name="requests")


# ---------------------------------------------------------------------------
# 共享工具
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "value,expected_year",
    [("2026-01-02T03:04:05Z", 2026), ("2026-01-02T03:04:05+00:00", 2026),
     ("2026-01-02 03:04:05", 2026), ("2026-01-02", 2026), ("", None), (None, None),
     ("garbage", None)],
)
def test_parse_dt(value, expected_year) -> None:
    dt = parse_dt(value)
    if expected_year is None:
        assert dt is None
    else:
        assert dt is not None and dt.year == expected_year


def test_guess_author_kind() -> None:
    assert guess_author_kind("dependabot[bot]") is AuthorKind.BOT
    assert guess_author_kind("someone", labels=["ai-generated"]) is AuthorKind.AI_AGENT
    assert guess_author_kind("dev", maintainers=["dev"]) is AuthorKind.MAINTAINER
    assert guess_author_kind("random") is AuthorKind.COMMUNITY
    assert guess_author_kind("") is AuthorKind.UNKNOWN
    assert guess_author_kind("x", body="Generated by Copilot") is AuthorKind.AI_AGENT


def test_extract_linked_issues() -> None:
    assert extract_linked_issues("fixes #42 and #43") == [42, 43]
    assert extract_linked_issues("see /issues/7") == [7]
    assert extract_linked_issues("closes /merge_requests/9") == [9]
    assert extract_linked_issues("nothing here") == []
    assert extract_linked_issues("#5 and #5") == [5]


def test_parse_repo_ref_variants() -> None:
    assert parse_repo_ref("a/b", Platform.GITHUB).slug == "a/b"
    assert parse_repo_ref("gitee:a/b").platform is Platform.GITEE
    assert parse_repo_ref("atomgit:o/n").platform is Platform.ATOMGIT
    with pytest.raises(Exception):
        parse_repo_ref("invalid")


def test_registry_build_and_urls(settings) -> None:
    for plat, cls in ADAPTERS.items():
        a = build_adapter(settings, platform=plat, token="tok")
        assert isinstance(a, cls)
        assert a.item_url(RepoRef(platform=plat, owner="o", name="n"), 3, ItemType.PR).startswith("https://")
        assert "***" in a.sanitize(a.clone_url(RepoRef(platform=plat, owner="o", name="n"), use_token=True))
    assert get_adapter_class(Platform.GITLAB) is GitLabAdapter


def test_resolve_repos_from_config_and_spec(settings) -> None:
    assert [r.slug for r in resolve_repos(settings, None)] == ["psf/requests"]
    assert [r.slug for r in resolve_repos(settings, ["psf/requests"])] == ["psf/requests"]
    # 未登记 → 临时构造
    out = resolve_repos(settings, ["gitee:other/repo"])
    assert out[0].slug == "other/repo" and out[0].platform is Platform.GITEE


# ---------------------------------------------------------------------------
# GitHub
# ---------------------------------------------------------------------------


@pytest.fixture
def gh(settings):
    adapter = build_adapter(settings, platform=Platform.GITHUB, token="t")
    yield adapter


@respx.mock
async def test_github_fetch_issue_and_pr(gh) -> None:
    respx.get(f"{GH}/repos/psf/requests/issues").mock(
        return_value=httpx.Response(
            200,
            json=[
                {
                    "number": 1, "title": "崩溃", "body": "boom", "state": "open",
                    "labels": [{"name": "bug"}], "user": {"login": "reporter"},
                    "created_at": "2026-01-01T00:00:00Z", "updated_at": "2026-01-02T00:00:00Z",
                    "html_url": "https://github.com/psf/requests/issues/1",
                },
                {
                    "number": 2, "title": "修复崩溃", "body": "closes #1", "state": "open",
                    "labels": [], "user": {"login": "dev"},
                    "created_at": "2026-01-03T00:00:00Z", "updated_at": "2026-01-04T00:00:00Z",
                    "pull_request": {"url": "https://api.github.com/..."},
                },
            ],
        )
    )
    respx.get(f"{GH}/repos/psf/requests/issues/1/comments").mock(
        return_value=httpx.Response(200, json=[
            {"user": {"login": "u2"}, "body": "me too", "created_at": "2026-01-02T01:00:00Z"}
        ])
    )
    respx.get(f"{GH}/repos/psf/requests/issues/2/comments").mock(return_value=httpx.Response(200, json=[]))
    respx.get(f"{GH}/repos/psf/requests/pulls/2").mock(
        return_value=httpx.Response(200, json={
            "base": {"ref": "main"}, "head": {"ref": "fix", "repo": {"full_name": "dev/requests"}},
            "merged_at": None, "mergeable": True, "draft": False,
            "additions": 5, "deletions": 1, "changed_files": 1, "title": "修复崩溃", "body": "closes #1",
        })
    )

    items = [i async for i in gh.fetch_items(REPO, item_types=[ItemType.ISSUE, ItemType.PR])]
    assert len(items) == 2

    issue = items[0]
    assert issue.number == 1 and issue.item_type is ItemType.ISSUE
    assert issue.labels == ["bug"] and issue.author == "reporter"
    assert len(issue.comments) == 1 and issue.comments[0].body == "me too"

    pr = items[1]
    assert pr.item_type is ItemType.PR
    assert pr.base_branch == "main" and pr.head_branch == "fix"
    assert pr.head_repo == "dev/requests"
    assert pr.additions == 5 and pr.changed_files == 1
    assert pr.linked_issues == [1]


@respx.mock
async def test_github_item_type_filter(gh) -> None:
    respx.get(f"{GH}/repos/psf/requests/issues").mock(
        return_value=httpx.Response(200, json=[
            {"number": 1, "title": "i", "state": "open", "labels": [], "user": {"login": "a"}},
            {"number": 2, "title": "p", "state": "open", "labels": [], "user": {"login": "b"},
             "pull_request": {"url": "x"}},
        ])
    )
    respx.get(f"{GH}/repos/psf/requests/issues/1/comments").mock(return_value=httpx.Response(200, json=[]))
    items = [i async for i in gh.fetch_items(REPO, item_types=[ItemType.ISSUE])]
    assert [i.number for i in items] == [1]


@respx.mock
async def test_github_rate_limit_retries_then_succeeds(gh) -> None:
    route = respx.get(f"{GH}/repos/psf/requests/issues").mock(
        side_effect=[
            httpx.Response(429, headers={"retry-after": "0"}),
            httpx.Response(200, json=[]),
        ]
    )
    items = [i async for i in gh.fetch_items(REPO)]
    assert items == []
    assert route.call_count == 2


@respx.mock
async def test_github_api_error_raises(gh) -> None:
    from fissue.errors import PlatformError

    respx.get(f"{GH}/repos/psf/requests/issues").mock(return_value=httpx.Response(404, text="not found"))
    with pytest.raises(PlatformError):
        [i async for i in gh.fetch_items(REPO)]


@respx.mock
async def test_github_diff_and_labels(gh) -> None:
    respx.get(f"{GH}/repos/psf/requests/pulls/5").mock(return_value=httpx.Response(200, text="diff --git a/x b/x"))
    assert "diff --git" in await gh.fetch_diff(REPO, 5)

    respx.get(f"{GH}/repos/psf/requests/labels").mock(return_value=httpx.Response(200, json=[{"name": "bug"}]))
    assert await gh.fetch_repo_labels(REPO) == ["bug"]

    add = respx.post(f"{GH}/repos/psf/requests/issues/1/labels").mock(return_value=httpx.Response(200, json=[]))
    await gh.add_labels(REPO, 1, ["bug", "fissue"])
    assert add.called


@respx.mock
async def test_github_default_branch_and_whoami(gh) -> None:
    respx.get(f"{GH}/repos/psf/requests").mock(return_value=httpx.Response(200, json={"default_branch": "main"}))
    respx.get(f"{GH}/user").mock(return_value=httpx.Response(200, json={"login": "me"}))
    assert await gh.get_default_branch(REPO) == "main"
    assert await gh.whoami() == "me"


@respx.mock
async def test_github_fork_and_create_pr(gh) -> None:
    respx.post(f"{GH}/repos/psf/requests/forks").mock(
        return_value=httpx.Response(200, json={"full_name": "me/requests"})
    )
    fork = await gh.fork_repo(REPO)
    assert fork.owner == "me" and fork.name == "requests"

    respx.post(f"{GH}/repos/psf/requests/pulls").mock(
        return_value=httpx.Response(201, json={"number": 9, "html_url": "https://github.com/psf/requests/pull/9"})
    )
    out = await gh.create_pr(REPO, head="me:fix", base="main", title="t", body="b")
    assert out["number"] == 9 and out["url"].endswith("/9")


# ---------------------------------------------------------------------------
# Gitee / AtomGit（v5 同构）
# ---------------------------------------------------------------------------


@pytest.fixture
def gitee(settings):
    return build_adapter(settings, platform=Platform.GITEE, token="t")


@pytest.fixture
def atomgit(settings):
    return build_adapter(settings, platform=Platform.ATOMGIT, token="t")


def test_v5_endpoints_and_headers(gitee, atomgit) -> None:
    assert gitee.api_base == GITEE
    assert atomgit.api_base == ATOMGIT
    assert atomgit._headers()["X-Api-Version"] == "2023-02-21"
    assert gitee._auth_params() == {"access_token": "t"}      # Gitee 走查询参数
    assert atomgit._auth_params() == {}
    assert atomgit.item_url(RepoRef(platform=Platform.ATOMGIT, owner="o", name="n"), 1, ItemType.ISSUE) \
        == "https://atomgit.com/o/n/issues/1"


@respx.mock
async def test_gitee_fetch_issue(gitee) -> None:
    respx.get(f"{GITEE}/repos/psf/requests/issues").mock(
        return_value=httpx.Response(200, json=[{
            "number": 3, "title": "报错", "body": "traceback", "state": "open",
            "labels": [{"name": "bug"}], "user": {"login": "u"}, "created_at": "2026-02-01T00:00:00+08:00",
        }])
    )
    respx.get(f"{GITEE}/repos/psf/requests/issues/3/comments").mock(return_value=httpx.Response(200, json=[]))
    items = [i async for i in gitee.fetch_items(REPO, item_types=[ItemType.ISSUE])]
    assert len(items) == 1
    assert items[0].labels == ["bug"] and items[0].author == "u"


@respx.mock
async def test_atomgit_fetch_pr_with_linked_issues(atomgit) -> None:
    respx.get(f"{ATOMGIT}/repos/psf/requests/pulls").mock(
        return_value=httpx.Response(200, json=[{"number": 8, "title": "pr", "state": "open"}])
    )
    respx.get(f"{ATOMGIT}/repos/psf/requests/pulls/8").mock(
        return_value=httpx.Response(200, json={
            "number": 8, "title": "pr", "body": "fix", "state": "open",
            "labels": [], "user": {"login": "dev"},
            "head": {"ref": "f", "repo": {"full_name": "dev/requests"}},
            "base": {"ref": "master"},
            "additions": 2, "deletions": 0, "changed_files": 1,
        })
    )
    respx.get(f"{ATOMGIT}/repos/psf/requests/pulls/8/issues").mock(
        return_value=httpx.Response(200, json=[{"number": 3}, {"number": 4}])
    )
    respx.get(f"{ATOMGIT}/repos/psf/requests/issues/8/comments").mock(return_value=httpx.Response(200, json=[]))

    items = [i async for i in atomgit.fetch_items(REPO, item_types=[ItemType.PR])]
    assert len(items) == 1
    pr = items[0]
    assert pr.base_branch == "master" and pr.head_repo == "dev/requests"
    assert pr.linked_issues == [3, 4]


@respx.mock
async def test_v5_label_and_comment_paths(gitee) -> None:
    respx.get(f"{GITEE}/repos/psf/requests/labels").mock(return_value=httpx.Response(200, json=[]))
    create = respx.post(f"{GITEE}/repos/psf/requests/labels").mock(return_value=httpx.Response(201, json={}))
    await gitee.ensure_label(REPO, "fissue")
    assert create.called

    comment = respx.post(f"{GITEE}/repos/psf/requests/issues/1/comments").mock(
        return_value=httpx.Response(201, json={})
    )
    await gitee.comment(REPO, 1, "hello")
    assert comment.called


# ---------------------------------------------------------------------------
# GitLab
# ---------------------------------------------------------------------------


@pytest.fixture
def gl(settings):
    return build_adapter(settings, platform=Platform.GITLAB, token="t")


def test_gitlab_host_derivation(settings) -> None:
    assert build_adapter(settings, platform=Platform.GITLAB).web_host == "gitlab.com"
    from fissue.config import RepoConfig

    custom = build_adapter(
        settings, RepoConfig(platform=Platform.GITLAB, owner="a", name="b", api_base="https://git.corp.io/api/v4")
    )
    assert custom.web_host == "git.corp.io"
    assert custom.api_base == "https://git.corp.io/api/v4"
    assert custom.item_url(RepoRef(platform=Platform.GITLAB, owner="a", name="b"), 4, ItemType.PR) \
        == "https://git.corp.io/a/b/-/merge_requests/4"


def test_gitlab_norm_state() -> None:
    assert _norm_state("opened") == "open"
    assert _norm_state("merged") == "merged"
    assert _norm_state(None) == "open"


def test_gitlab_project_id_encoding(gl) -> None:
    assert gl._pid(RepoRef(platform=Platform.GITLAB, owner="a b", name="c")) == "a%20b%2Fc"


@respx.mock
async def test_gitlab_fetch_issue_and_mr(gl) -> None:
    pid = "psf%2Frequests"
    respx.get(f"{GL}/projects/{pid}/issues").mock(
        return_value=httpx.Response(200, json=[{
            "iid": 5, "title": "bug", "description": "desc", "state": "opened",
            "labels": ["bug"], "author": {"username": "u"}, "created_at": "2026-03-01T00:00:00Z",
            "web_url": "https://gitlab.com/psf/requests/-/issues/5",
        }])
    )
    respx.get(f"{GL}/projects/{pid}/issues/5/notes").mock(
        return_value=httpx.Response(200, json=[
            {"body": "系统事件", "system": True, "author": {"username": "bot"}},
            {"body": "我来看看", "system": False, "author": {"username": "m"}},
        ])
    )
    respx.get(f"{GL}/projects/{pid}/merge_requests").mock(
        return_value=httpx.Response(200, json=[{
            "iid": 6, "title": "mr", "description": "closes #5", "state": "opened",
            "labels": [], "author": {"username": "d"}, "target_branch": "main",
            "source_branch": "fix", "merge_status": "can_be_merged",
        }])
    )
    respx.get(f"{GL}/projects/{pid}/merge_requests/6/changes").mock(
        return_value=httpx.Response(200, json={
            "additions": 7, "deletions": 2,
            "changes": [{"old_path": "a.py", "new_path": "a.py", "diff": "@@ -1 +1 @@\n-x\n+y\n"}],
        })
    )
    respx.get(f"{GL}/projects/{pid}/merge_requests/6/notes").mock(return_value=httpx.Response(200, json=[]))

    items = [i async for i in gl.fetch_items(REPO, item_types=[ItemType.ISSUE, ItemType.PR])]
    assert len(items) == 2

    issue = [i for i in items if i.item_type is ItemType.ISSUE][0]
    assert issue.number == 5 and issue.state == "open"
    assert len(issue.comments) == 1                  # system 事件被过滤
    assert issue.comments[0].body == "我来看看"

    mr = [i for i in items if i.item_type is ItemType.PR][0]
    assert mr.base_branch == "main" and mr.head_branch == "fix"
    assert mr.additions == 7 and mr.changed_files == 1
    assert mr.linked_issues == [5]


@respx.mock
async def test_gitlab_merge_request_diff(gl) -> None:
    pid = "psf%2Frequests"
    respx.get(f"{GL}/projects/{pid}/merge_requests/6/changes").mock(
        return_value=httpx.Response(200, json={
            "changes": [{"old_path": "x.py", "new_path": "x.py", "diff": "@@ -1 +1 @@\n-a\n+b\n"}]
        })
    )
    diff = await gl.fetch_diff(REPO, 6)
    assert "--- a/x.py" in diff and "+++ b/x.py" in diff


@respx.mock
async def test_gitlab_add_labels_and_close(gl) -> None:
    pid = "psf%2Frequests"
    put = respx.put(f"{GL}/projects/{pid}/issues/5").mock(return_value=httpx.Response(200, json={}))
    await gl.add_labels(REPO, 5, ["fissue", "bug"])
    await gl.close_item(REPO, 5)
    assert put.call_count == 2


@respx.mock
async def test_gitlab_create_mr_across_projects(gl) -> None:
    pid = "psf%2Frequests"
    respx.get(f"{GL}/projects/{pid}").mock(return_value=httpx.Response(200, json={"id": 111}))
    created = respx.post(f"{GL}/projects/me%2Frequests/merge_requests").mock(
        return_value=httpx.Response(201, json={"iid": 10, "web_url": "https://gitlab.com/psf/requests/-/merge_requests/10"})
    )
    out = await gl.create_pr(REPO, head="me/requests:fix", base="main", title="t", body="b")
    assert out["number"] == 10
    body = json.loads(created.calls[0].request.content)
    assert body["source_branch"] == "fix"
    assert body["target_project_id"] == 111


# ---------------------------------------------------------------------------
# 限流头解析
# ---------------------------------------------------------------------------


def test_retry_after_parsing() -> None:
    from fissue.platforms.base import _parse_retry_after

    r = httpx.Response(429, headers={"retry-after": "3"})
    assert _parse_retry_after(r) == 3.0
    r2 = httpx.Response(429)
    assert _parse_retry_after(r2) == 5.0
